name: obsidiangate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  supabase_flutter: ^2.0.3
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/fonts/PretendardVariable.woff2
    - assets/icons/chat.png
    - assets/icons/kakao.png
    - assets/icons/Discord.png
    - assets/icons/Telegram.png
    - assets/icons/Wechat.png
    - assets/icons/logo.png
    - assets/sidelogo.png

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.woff2
